In [1]:
print('Hello')

Hello


Yeah Python!!

In [3]:
import numpy as np

In [5]:
my_list = [1,2,3]


In [6]:
np.array(my_list)

array([1, 2, 3])

In [9]:
# its arange and not arrange for arranging the array

In [10]:
np.arange(0,19,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0,10,5) #gives out values between equal intervals

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.random.rand(5) # random distribution between 0 and 1

array([0.475541  , 0.95159806, 0.02946495, 0.35518893, 0.59611601])

In [17]:
np.random.randn(5) # standard normal distribution 

array([ 0.2694744 , -1.20521065, -0.31934669,  1.18680022, -0.00773849])

In [20]:
np.random.randint(5) # random integer with upperbound

3

In [22]:
np.zeros((2,3)) #array of zero's tuple is specified for dimensions

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])