In [93]:
print('Hello')

Hello


Yeah!! Learning numpy

In [94]:
import numpy as np

In [95]:
my_list = [1,2,3]


In [96]:
np.array(my_list)

array([1, 2, 3])

In [97]:
# its arange and not arrange for arranging the array

In [98]:
np.arange(0,19,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
np.linspace(0,10,5) #gives out values between equal intervals

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [100]:
np.random.rand(5) # random distribution between 0 and 1

array([0.90800521, 0.34400999, 0.1472432 , 0.60538672, 0.02017543])

In [101]:
np.random.randn(5) # standard normal distribution 

array([-1.46955064, -0.09621303,  0.36471826, -0.1079932 ,  0.86065895])

In [102]:
np.random.randint(5) # random integer with upperbound

3

In [103]:
np.zeros((2,3)) #array of zero's tuple is specified for dimensions

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
array1 = np.arange(25)

In [106]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
array2 = np.random.randint(0,50,10)

In [108]:
array2

array([ 8, 46, 27, 44, 17, 16, 33, 19, 48, 10])

In [109]:
new_array = array1.reshape(5,5) # reshapes the array into specified array shape

In [110]:
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
array2.max()

48

In [112]:
array2.min()

8

In [113]:
array2.argmin() # retirns the positon of the min value

0

In [114]:
array2.argmax()

8

In [115]:
array1.shape #shape of an array

(25,)

In [116]:
array1.dtype # data type of array

dtype('int32')

In [117]:
first_array = np.arange(25)

In [118]:
first_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [119]:
new_array = first_array[0:5] # slicing the array

In [120]:
new_array[:] = 99 #changing all the values inside the array

In [121]:
new_array

array([99, 99, 99, 99, 99])

In [122]:
first_array # When we silce the first array. The values of the original array's change too. 

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [123]:
first_array = np.arange(25)

In [124]:
first_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [125]:
first_array_copy = first_array[0:4].copy() # Using the .copy() method does not make a change in the original array. 

In [126]:
first_array_copy

array([0, 1, 2, 3])

In [127]:
first_array_copy[:] = 99

In [128]:
first_array_copy

array([99, 99, 99, 99])

In [129]:
first_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [130]:
arr_ay = np.arange(1,26).reshape(5,5)

In [131]:
arr_ay

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [132]:
arr_ay[0][0] # In array Indexing. First sqr bracket represents the row and the second one represents the column. 
#Using double brackets is inefficient

1

In [133]:
arr_ay[0,0] # Using single braket for referencing the element

1

In [134]:
new_arr_ay = arr_ay[2:,2:] # selecting elements using indexing

In [135]:
new_arr_ay

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [136]:
arr_ay[:2,3:] # one more example of sub matrix

array([[ 4,  5],
       [ 9, 10]])

In [137]:
arr = np.arange(1,11)

In [138]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
boolarr = arr > 5 # Using boolean logic

In [140]:
boolarr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [141]:
arr[boolarr] # Returns outcomes where bool is true

array([ 6,  7,  8,  9, 10])

In [142]:
arr[arr>3] # Returns array based on condition. This is the shortcut method instead of using the longer one.

array([ 4,  5,  6,  7,  8,  9, 10])

In [143]:
np.array(0)

array(0)

In [144]:
import numpy as np
arr = np.arange(0,10)

In [145]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [146]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [147]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [148]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-148-2f119c028196>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [149]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-149-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [150]:
arr**3

## Universal Array Functions

#Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:



array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [151]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [152]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [153]:
np.max(arr) #same as arr.max()

9

In [154]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [155]:
np.log(arr)

<ipython-input-155-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])